spring.application.name=ExerciseTracker

# H2 DATABASE CONNECTION
#spring.datasource.url=jdbc:h2:file:/Users/vikrampratha/h2/exercise-tracker-db;AUTO_SERVER=TRUE;
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# POSTGRES DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/extrackdb
spring.datasource.username=extrack
spring.datasource.password=extrack

# H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# HIBERNATE/JPA
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=wSSe8gKPvYwKDZEmbgfdEus4vNtJIJN3tPDmcjgdfbs=
app.jwt.expirationMinutes=10080

# LOGGING
logging.level.org.springframework.security=INFO

